### PR TITLE
added check for non-existent file path

### PR DESCRIPTION
**Pull request by dcoffey3296**
added a check if dirPath is returned as an empty string.  For https://github.com/Olian04/better-logging/issues/49

### CODE REVIEW

**Comment by dcoffey3296** [comment]
It was indeed the single quotes, though `npm run lint` didn't catch it locally.  Thanks!

**Comment by Olian04** [comment]
I'll have to do some manual tests, just to make sure that this wont mess with any other valid path strings.
If all checks out, this will be part of the next patch release :)

**Comment by dcoffey3296** [comment]
👍😀

**Comment by Olian04** [comment]
This change is now included in release 4.4.1

**Pull request merged**
